#https://medium.com/@nikmas_dev/vscode-neovim-setup-keyboard-centric-powerful-reliable-clean-and-aesthetic-development-582d34297985
if patched_font_in_use; then
 TMUX_POWERLINE_SEPARATOR_LEFT_BOLD=""
 TMUX_POWERLINE_SEPARATOR_LEFT_THIN=":"
 TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD=""
 TMUX_POWERLINE_SEPARATOR_RIGHT_THIN=":"
else
 TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="◀"
 TMUX_POWERLINE_SEPARATOR_LEFT_THIN="❮"
 TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="▶"
 TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="❯"
fi

TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR:-'235'}
TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR:-'255'}
TMUX_POWERLINE_SEG_AIR_COLOR=$(air_color)

TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD}
TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_LEFT_BOLD}

if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_CURRENT" ]; then
 TMUX_POWERLINE_WINDOW_STATUS_CURRENT=(
    "#[bg=#010408]"
  "$TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR"
  # " #I"
  " #I#F"
  "$TMUX_POWERLINE_SEPARATOR_RIGHT_THIN"
  " #W "
  "#[$(format regular)]"
  "$TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR"
 )
fi

if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_STYLE" ]; then
 TMUX_POWERLINE_WINDOW_STATUS_STYLE=(
  "$(format regular)"
 )
fi

if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_FORMAT" ]; then
 TMUX_POWERLINE_WINDOW_STATUS_FORMAT=(
  "#[$(format regular)]"
  # " #I"
	" #I#{?window_flags,#F,}"
  "$TMUX_POWERLINE_SEPARATOR_RIGHT_THIN"
  " #W "
 )
fi

TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=()
TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=()
